// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAz5DXc2eSocVAjdYHgSnwlzIN2KmTcI-o',
    appId: '1:478110597889:web:fb713066ba9862c53d9100',
    messagingSenderId: '478110597889',
    projectId: 'mobilprojem-19677',
    authDomain: 'mobilprojem-19677.firebaseapp.com',
    storageBucket: 'mobilprojem-19677.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABNDxik_5xGsNR-rNCtqSKzNG3mTapbyM',
    appId: '1:478110597889:android:f55c04c09c2d94ab3d9100',
    messagingSenderId: '478110597889',
    projectId: 'mobilprojem-19677',
    storageBucket: 'mobilprojem-19677.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAnOWZfqZGGW9dTo14EzJkYZGS3PdGxAI',
    appId: '1:478110597889:ios:0648161f5245989f3d9100',
    messagingSenderId: '478110597889',
    projectId: 'mobilprojem-19677',
    storageBucket: 'mobilprojem-19677.appspot.com',
    iosClientId: '478110597889-h7hdbqa2fqqmi9jmj6rukor965oultel.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobilProjem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAnOWZfqZGGW9dTo14EzJkYZGS3PdGxAI',
    appId: '1:478110597889:ios:87dd63cb74a943833d9100',
    messagingSenderId: '478110597889',
    projectId: 'mobilprojem-19677',
    storageBucket: 'mobilprojem-19677.appspot.com',
    iosClientId: '478110597889-qp17upqc0sat2j52v0n6p9r81ih9j8lj.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobilProjem.RunnerTests',
  );
}
